In [7]:
import cv2
from PIL import Image
from keras.models import load_model
import numpy as np
from keras.preprocessing import image
model=load_model('facefeatures_new_model.h5')

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    if faces is ():
        return None
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        cropped_face=img[y:y+h,x:x+w]
    return cropped_face
        
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face=cv2.resize(face,(224,224))
        im=Image.fromarray(face,'RGB')
        
        img_array=np.array(im)
        img_array=np.expand_dims(img_array,axis=0)
        pred=model.predict(img_array)
        print(pred)
        
        name=" None Matching"
        
        if(pred[0][0]>0.5):
            name='chetan'
            cv2.putText(frame,name,(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
        elif(pred[0][1]>0.5):
            name='daddy'
            cv2.putText(frame,name,(00,185),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
        elif(pred[0][2]>0.5):
            name='abhishek'
            cv2.putText(frame,name,(00,285),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        else:
            cv2.putText(frame,'not matching',(50,385),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
            
    else:
        cv2.putText(frame,'No Face Found',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[9.8591382e-15 9.4996555e-29 1.0000000e+00]]
[[4.1580354e-27 0.0000000e+00 1.0000000e+00]]
[[2.7281092e-07 5.4012849e-24 9.9999976e-01]]
[[1.2412360e-16 9.9970043e-01 2.9954352e-04]]
[[1.3827747e-09 3.2584689e-26 1.0000000e+00]]
[[2.1824539e-07 1.6923326e-22 9.9999976e-01]]
[[3.1869223e-16 9.6393329e-01 3.6066696e-02]]
[[2.3531787e-19 9.9598640e-01 4.0135356e-03]]
[[7.3225226e-07 4.0924004e-18 9.9999928e-01]]
[[4.9872937e-19 1.8676641e-35 1.0000000e+00]]
[[1.6781855e-12 3.0766234e-30 1.0000000e+00]]
[[3.0566767e-12 1.1248767e-27 1.0000000e+00]]
[[9.690186e-24 8.216280e-37 1.000000e+00]]
[[8.0169736e-16 5.7285768e-01 4.2714235e-01]]
[[1.0529776e-27 1.9156675e-38 1.0000000e+00]]
[[8.4831436e-29 0.0000000e+00 1.0000000e+00]]
[[1.8594755e-19 2.3552789e-37 1.0000000e+00]]
[[1.6334263e-06 1.7837231e-01 8.2162607e-01]]
[[5.5235246e-04 9.9944562e-01 2.0462355e-06]]
[[4.0447684e-27 9.3231396e-35 1.0000000e+00]]
[[1.2967007e-22 6.6653422e-26 1.0000000e+00]]
[[2.1655102e-29 0.0000000e+00 1.00000